### ISSUE TITLE
Download theme error

### ISSUE THREAD

**Issue by d0dUxDJ** [Rinnegatamante/CHMM2#10]
Error: [string "?"]:1042: bad argument #4 to 'print' (string expected, got nil) <<<<<< when trying to download any theme. Latest CHMM2 release, files in correct folders and so on. Tried to redownload the package twice, as well as deleting and re-installing the .cia twice.
Launching from HBL gives same result. After "nil)" there appears to be a random character every time, mostly "h" or a square.

**Comment by Rinnegatamante** [comment]
Can you upload somewhere your localization file?

**Comment by d0dUxDJ** [comment]
There you go. http://pastebin.com/xmdQCk5G

**Comment by Rinnegatamante** [comment]
File looks corrupt, replace downloading variable with downloadingth.

**Comment by d0dUxDJ** [comment]
It works now! Checked the zip, downloading it once again from your site; the variable is still called "downloading", so it wasn't corrupt, it's just wrong in the zip. Thanks though.
