### ISSUE TITLE
Audio for themes doesn't always carry over.

### ISSUE THREAD

**Issue by Zetchzie** [Rinnegatamante/CHMM2#2]
When I install a theme sometimes the music from the last theme stays.

Ill Download a theme from 3DSThemes and Install it and it will have its own music but when I install a different theme that has its own music the last themes music is still there. Is this The theme creators fault or a bug in CHMM

**Comment by Rinnegatamante** [comment]
It's caused by a bug in YATA+ (Tool used to create themes).

**Comment by Zetchzie** [comment]
Alright ^^ thanks sorry to bug you.
