### ISSUE TITLE
Error:[string "?"]:1: unexpected symbol near '<\156>'

### ISSUE THREAD

**Issue by Savior93** [Rinnegatamante/CHMM2#3]
Ciao,quando provo ad aprire chmm ricevo questo errore "Error:[string "?"]:1: unexpected symbol near '<\156>' " ,utilizzo l'ultima versione che hai rilasciato,come posso risolvere?

**Comment by Rinnegatamante** [comment]
I suggest you to place the question on official topic on GBAtemp. Same issue was encountered and solved by several users.
