### ISSUE TITLE
Error: [string "?"]:3: unexpected symbol near '4'

### ISSUE THREAD

**Issue by Boured** [Rinnegatamante/CHMM2#5]
For some reason this happens everytime I start it now, It just happened and I have no idea why.

**Comment by ihaveamac** [comment]
does deleting "settings.cfg" in the Themes folder fix this?

**Comment by Boured** [comment]
Apparently that was what was wrong, thanks guy who likes to say they have a mac :3

**Comment by Rinnegatamante** [comment]
If you get caught in the same error another time, can you please send me the settings.cfg file? I want to investigate this bug to fix it.
