### ISSUE TITLE
CHMM2 on 64GB card problem???

### ISSUE THREAD

**Issue by Shadow322** [Rinnegatamante/CHMM2#7]
Every time I run it, it asks me everytime if my nands r linked and i click NO is they r linked then when i apply a theme and go back to 3ds menu theme isnt applyed also when I go to settings menu of CHMM2 set some settings exit CHMM2 the settings arnt saved. and also says Menuhax Mode: ON

**Comment by Rinnegatamante** [comment]
Please write in correct english, your issue is kinda hard to read. Anyway, run Menuhax Manager on emuNand using hblauncher_loader and then remove menuhax files.

**Comment by Shadow322** [comment]
I never ran menuhax manager on this 3ds.

**Comment by Shadow322** [comment]
Ok I ran menuhax manager and it had no effect CHMM2 still says MenuHax
Mode: ON seems your software has problems with SDXC cards

**Comment by Rinnegatamante** [comment]
No, since Menuhax mode is showed only if shufflehax or menuhax is detected: https://github.com/Rinnegatamante/CHMM2/blob/master/source/index.lua#L875-L877
