### ISSUE TITLE
 Constant warning on CIA build

### ISSUE THREAD

**Issue by PokeAcer549** [Rinnegatamante/CHMM2#8]
Can the warning for NAND linking be disabled after so long? It gets annoying; aswell as the power button requirement.

**Comment by Rinnegatamante** [comment]
They're both required for the correct functionallity of the homebrew.

**Comment by PokeAcer549** [comment]
How so? THe former could be set as a config; read this config and then no more asking, and the latter makes more sense but still..

**Comment by Rinnegatamante** [comment]
Saving the choice to a config doesn't prevent you to not unlink/relink your nands. If something will change in the system, CHMM2 will not be able to understand that, breaking completely the whole homebrew functionallity.

As for the Power button, i stated several times on forums and twitter that it's required for the theme application without hardreset.
