### ISSUE TITLE
Compiling fails.

### ISSUE THREAD

**Issue by Sans0Serif** [Rinnegatamante/CHMM2#9]
Attempting to compile with build.bat (or make) after acquiring arm-none-eabi-strip fails with:

c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/5.3.0/../../../../arm-none-eabi/bin/ld.exe: cannot find 3dsx_crt0.o: No such file or directory

After looking around, this seems to be an issue from devkitARM r44, from **Feb 15, 2015.** Attempting to use the "fix" suggested in the dkA release post of changing -mfloat-abi=softfp in the Makefile to -mfloat-abi=hard and make clean & rebuilding results in a few pages full of:

arm-none-eabi/bin/ld.exe: failed to merge target specific data of file

and

CHMM2.elf uses VFP register arguments, <X> does not.

**Comment by Rinnegatamante** [comment]
Floating point mode shouldn't be changed.

You must go to /devkitPro/devkitARM/arm-none-eabi/lib and you should execute a "make CRT=3dsx".
